# Generated by Django 3.0.3 on 2020-03-20 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TodoItem',
        ),
    ]
